# Bug Fix Template
name: バグ修正
description: 軽微なバグの修正用テンプレート
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        このテンプレートは軽微なバグ修正のために使用してください。
        大規模な改修が必要な場合は、Notionのプロダクトバックログに記載してください。
  
  - type: input
    id: affected-page
    attributes:
      label: 影響範囲
      description: バグが発生しているページやコンポーネント
      placeholder: "例: ログインページ、ヘッダーコンポーネント"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: 現在の動作
      description: バグの具体的な症状
      placeholder: "例: ログインボタンをクリックしても反応がない"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      description: 正常な場合の期待される動作
      placeholder: "例: ログインボタンをクリックするとログイン処理が実行される"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      description: バグを再現するための手順
      placeholder: |
        1. ログインページにアクセス
        2. メールアドレスとパスワードを入力
        3. ログインボタンをクリック
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: 修正の優先度を選択してください
      options:
        - Low（影響は軽微）
        - Medium（ユーザー体験に影響あり）
        - High（機能が正常に動作しない）
    validations:
      required: true
