# Bug Fix Template
name: バグ修正
description: 軽微なバグの修正用テンプレート
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        このテンプレートは軽微なバグ修正のために使用してください。
        大規模な改修が必要な場合は、Notionのプロダクトバックログに記載してください。
  
  - type: input
    id: affected-page
    attributes:
      label: 影響範囲
      description: バグが発生しているページやコンポーネント
      placeholder: "例: ログインページ、ヘッダーコンポーネント"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: 現在の動作
      description: バグの具体的な症状
      placeholder: "例: ログインボタンをクリックしても反応がない"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      description: 正常な場合の期待される動作
      placeholder: "例: ログインボタンをクリックするとログイン処理が実行される"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      description: バグを再現するための手順
      placeholder: |
        1. ログインページにアクセス
        2. メールアドレスとパスワードを入力
        3. ログインボタンをクリック
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: 修正の優先度を選択してください
      options:
        - Low（影響は軽微）
        - Medium（ユーザー体験に影響あり）
        - High（機能が正常に動作しない）
    validations:
      required: true

# Technical Improvement Template
name: 技術的改善
description: インフラ改善やパフォーマンス最適化用テンプレート
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        このテンプレートは小規模な技術的改善のために使用してください。
        大規模な改修が必要な場合は、Notionのプロダクトバックログに記載してください。

  - type: dropdown
    id: improvement-type
    attributes:
      label: 改善タイプ
      description: 改善の種類を選択してください
      options:
        - インフラ改善
        - パフォーマンス最適化
        - セキュリティ対応
        - 依存パッケージの更新
        - その他
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: 現状
      description: 現在の状況や課題
      placeholder: "例: ページの読み込みに3秒以上かかっている"
    validations:
      required: true

  - type: textarea
    id: improvement-details
    attributes:
      label: 改善内容
      description: 具体的な改善内容
      placeholder: "例: 画像の最適化による読み込み時間の短縮"
    validations:
      required: true

  - type: textarea
    id: expected-impact
    attributes:
      label: 期待される効果
      description: 改善による具体的な効果
      placeholder: "例: ページ読み込み時間を1秒以下に短縮"
    validations:
      required: true

  - type: dropdown
    id: impact-level
    attributes:
      label: 影響度
      description: 改善による影響の大きさを選択してください
      options:
        - Low（局所的な改善）
        - Medium（複数機能への影響あり）
        - High（システム全体への影響あり）
    validations:
      required: true

# UI/UX Fix Template
name: UI/UX修正
description: 軽微なUI/UXの修正用テンプレート
labels: ["ui/ux"]
body:
  - type: markdown
    attributes:
      value: |
        このテンプレートは軽微なUI/UX修正のために使用してください。
        大規模な改修が必要な場合は、Notionのプロダクトバックログに記載してください。

  - type: input
    id: target-component
    attributes:
      label: 対象コンポーネント
      description: 修正が必要なコンポーネントやページ
      placeholder: "例: ナビゲーションメニュー、フォームコンポーネント"
    validations:
      required: true

  - type: textarea
    id: current-design
    attributes:
      label: 現在のデザイン
      description: 現在のUI/UXの状況
      placeholder: "例: ボタンのテキストが小さすぎて読みづらい"
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: 提案する変更
      description: 具体的な修正内容
      placeholder: "例: ボタンのフォントサイズを16pxに変更"
    validations:
      required: true

  - type: textarea
    id: reason-for-change
    attributes:
      label: 変更理由
      description: なぜこの変更が必要か
      placeholder: "例: ユーザーからの読みづらいというフィードバックに対応するため"
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: 影響範囲
      description: 修正の影響範囲を選択してください
      options:
        - 単一コンポーネント
        - 複数コンポーネント
        - ページ全体
    validations:
      required: true
